# Generated by Django 4.2.3 on 2023-07-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_rename_dept_name_employee_dept_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='dept_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dept',
        ),
        migrations.AddField(
            model_name='employee',
            name='role_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
