# Generated by Django 4.2.3 on 2023-07-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_role_employee_dept_name_remove_employee_dept_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.TextField(max_length=500)),
                ('timestemp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
