# Generated by Django 4.2.3 on 2023-07-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
